### ISSUE TITLE
finner ikke at steder.json blir produsert i build katalogen

### ISSUE THREAD

**Issue by steinho** [Artsdatabanken/stedsnavn-lastejobb#3]
deploy peker på den - men ser ikke at den blir produsert..

Er det stednavn.txt det skal være? Som endelig output?

**Comment by bjornreppen** [comment]
Noen tenkte på et tidspunkt at .txt var et bedre navn enn .json, uten å fullføre jobben.  APIet forventet fortsatt .json og var fornøyd med den gamle fila.

Fikset i https://github.com/Artsdatabanken/stedsnavn-lastejobb/commit/8daad40e48d5c2e44d1378b1f368c9e859cd7230 og https://github.com/Artsdatabanken/stedsnavn-api/commit/2ce760d69025b489c05d95f4dc99c6fd4ac4a3e6
